# Generated by Django 5.0.4 on 2024-04-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_frame', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoframe',
            options={'verbose_name': 'Video Frame', 'verbose_name_plural': 'Video Frames'},
        ),
    ]
