# Generated by Django 5.0.4 on 2024-04-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_frame', '0003_alter_videoframe_frame_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoframe',
            name='frame_image',
            field=models.ImageField(upload_to='videos_frame/'),
        ),
        migrations.AlterField(
            model_name='videoframe',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
