# Generated by Django 5.0.4 on 2024-04-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_frame', '0004_alter_videoframe_frame_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoframe',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
