# Generated by Django 5.0.4 on 2024-04-28 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTSUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'RTSUrl',
                'verbose_name_plural': 'RTSUrls',
            },
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='RTSUrl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.rtsurl'),
        ),
    ]
