# Generated by Django 5.0.4 on 2024-04-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTSUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(max_length=500)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'RTSUrl',
                'verbose_name_plural': 'RTSUrls',
            },
        ),
    ]
