# Generated by Django 5.0.4 on 2024-04-27 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_rtsurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='RTSUrl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.rtsurl'),
        ),
    ]
