# Generated by Django 5.0.4 on 2024-04-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_rtsurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtsurl',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
