# Generated by Django 5.0.4 on 2024-04-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_rtsurl_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtsurl',
            name='URL',
            field=models.CharField(max_length=500),
        ),
    ]
